# Pandas - Data Cleaning

In [24]:
import pandas as pd

In [26]:
df=pd.read_csv("salary_data.csv")

In [28]:
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [30]:
df.head()  #For viewing first rows of data

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [32]:
df.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [36]:
df.shape

(30, 2)

In [38]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

In [40]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [46]:
df["Salary"]

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [52]:
df[(df["Salary"]>80000) & (df["YearsExperience"]>5.5) ]   #conditional Filtering

    YearsExperience    Salary
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
df[df[].between(5.5,7.2)

In [54]:
df.sort_values("Salary")

    YearsExperience    Salary
2               1.5   37731.0
0               1.1   39343.0
4               2.2   39891.0
3               2.0   43525.0
1               1.3   46205.0
7               3.2   54445.0
11              4.0   55794.0
5               2.9   56642.0
12              4.0   56957.0
13              4.1   57081.0
9               3.7   57189.0
6               3.0   60150.0
14              4.5   61111.0
10              3.9   63218.0
8               3.2   64445.0
16              5.1   66029.0
15              4.9   67938.0
18              5.9   81363.0
17              5.3   83088.0
20              6.8   91738.0
19              6.0   93940.0
21              7.1   98273.0
22              7.9  101302.0
25              9.0  105582.0
24              8.7  109431.0
27              9.6  112635.0
23              8.2  113812.0
26              9.5  116969.0
29             10.5  121872.0
28             10.3  122391.0

In [56]:
df.rename(
    columns={
        "Salary":"Income"
    },
    inplace=True
)

In [58]:
df

    YearsExperience    Income
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
df.columns=df.columns.str.lower()

In [ ]:
str.strip()  #to remove spaces

In [60]:
df["Bonus"] = df["Income"] * 0.20

In [62]:
df

    YearsExperience    Income    Bonus
0               1.1   39343.0   7868.6
1               1.3   46205.0   9241.0
2               1.5   37731.0   7546.2
3               2.0   43525.0   8705.0
4               2.2   39891.0   7978.2
5               2.9   56642.0  11328.4
6               3.0   60150.0  12030.0
7               3.2   54445.0  10889.0
8               3.2   64445.0  12889.0
9               3.7   57189.0  11437.8
10              3.9   63218.0  12643.6
11              4.0   55794.0  11158.8
12              4.0   56957.0  11391.4
13              4.1   57081.0  11416.2
14              4.5   61111.0  12222.2
15              4.9   67938.0  13587.6
16              5.1   66029.0  13205.8
17              5.3   83088.0  16617.6
18              5.9   81363.0  16272.6
19              6.0   93940.0  18788.0
20              6.8   91738.0  18347.6
21              7.1   98273.0  19654.6
22              7.9  101302.0  20260.4
23              8.2  113812.0  22762.4
24              8.7  109431.0  21886.2
25              9.0  105582.0  21116.4
26              9.5  116969.0  23393.8
27              9.6  112635.0  22527.0
28             10.3  122391.0  24478.2
29             10.5  121872.0  24374.4

In [64]:
df["Bonus"] = df["Bonus"] + 2000 #update your data

In [66]:
df

    YearsExperience    Income    Bonus
0               1.1   39343.0   9868.6
1               1.3   46205.0  11241.0
2               1.5   37731.0   9546.2
3               2.0   43525.0  10705.0
4               2.2   39891.0   9978.2
5               2.9   56642.0  13328.4
6               3.0   60150.0  14030.0
7               3.2   54445.0  12889.0
8               3.2   64445.0  14889.0
9               3.7   57189.0  13437.8
10              3.9   63218.0  14643.6
11              4.0   55794.0  13158.8
12              4.0   56957.0  13391.4
13              4.1   57081.0  13416.2
14              4.5   61111.0  14222.2
15              4.9   67938.0  15587.6
16              5.1   66029.0  15205.8
17              5.3   83088.0  18617.6
18              5.9   81363.0  18272.6
19              6.0   93940.0  20788.0
20              6.8   91738.0  20347.6
21              7.1   98273.0  21654.6
22              7.9  101302.0  22260.4
23              8.2  113812.0  24762.4
24              8.7  109431.0  23886.2
25              9.0  105582.0  23116.4
26              9.5  116969.0  25393.8
27              9.6  112635.0  24527.0
28             10.3  122391.0  26478.2
29             10.5  121872.0  26374.4

In [76]:
df.drop(0)

    YearsExperience    Income    Bonus
1               1.3   46205.0  11241.0
2               1.5   37731.0   9546.2
3               2.0   43525.0  10705.0
4               2.2   39891.0   9978.2
5               2.9   56642.0  13328.4
6               3.0   60150.0  14030.0
7               3.2   54445.0  12889.0
8               3.2   64445.0  14889.0
9               3.7   57189.0  13437.8
10              3.9   63218.0  14643.6
11              4.0   55794.0  13158.8
12              4.0   56957.0  13391.4
13              4.1   57081.0  13416.2
14              4.5   61111.0  14222.2
15              4.9   67938.0  15587.6
16              5.1   66029.0  15205.8
17              5.3   83088.0  18617.6
18              5.9   81363.0  18272.6
19              6.0   93940.0  20788.0
20              6.8   91738.0  20347.6
21              7.1   98273.0  21654.6
22              7.9  101302.0  22260.4
23              8.2  113812.0  24762.4
24              8.7  109431.0  23886.2
25              9.0  105582.0  23116.4
26              9.5  116969.0  25393.8
27              9.6  112635.0  24527.0
28             10.3  122391.0  26478.2
29             10.5  121872.0  26374.4

In [78]:
df.isnull()

    YearsExperience  Income  Bonus
0             False   False  False
1             False   False  False
2             False   False  False
3             False   False  False
4             False   False  False
5             False   False  False
6             False   False  False
7             False   False  False
8             False   False  False
9             False   False  False
10            False   False  False
11            False   False  False
12            False   False  False
13            False   False  False
14            False   False  False
15            False   False  False
16            False   False  False
17            False   False  False
18            False   False  False
19            False   False  False
20            False   False  False
21            False   False  False
22            False   False  False
23            False   False  False
24            False   False  False
25            False   False  False
26            False   False  False
27            False   False  False
28            False   False  False
29            False   False  False

In [80]:
df.isnull().sum()

YearsExperience    0
Income             0
Bonus              0
dtype: int64

In [82]:
df.dropna()

    YearsExperience    Income    Bonus
0               1.1   39343.0   9868.6
1               1.3   46205.0  11241.0
2               1.5   37731.0   9546.2
3               2.0   43525.0  10705.0
4               2.2   39891.0   9978.2
5               2.9   56642.0  13328.4
6               3.0   60150.0  14030.0
7               3.2   54445.0  12889.0
8               3.2   64445.0  14889.0
9               3.7   57189.0  13437.8
10              3.9   63218.0  14643.6
11              4.0   55794.0  13158.8
12              4.0   56957.0  13391.4
13              4.1   57081.0  13416.2
14              4.5   61111.0  14222.2
15              4.9   67938.0  15587.6
16              5.1   66029.0  15205.8
17              5.3   83088.0  18617.6
18              5.9   81363.0  18272.6
19              6.0   93940.0  20788.0
20              6.8   91738.0  20347.6
21              7.1   98273.0  21654.6
22              7.9  101302.0  22260.4
23              8.2  113812.0  24762.4
24              8.7  109431.0  23886.2
25              9.0  105582.0  23116.4
26              9.5  116969.0  25393.8
27              9.6  112635.0  24527.0
28             10.3  122391.0  26478.2
29             10.5  121872.0  26374.4

In [ ]:
df["salary"] =df["salary"].fillna("unknown values")   #for filling with constant

In [ ]:
df["salary"] = df["salary"].fillna()(df["salary"].mean())    #numerical and data should not contain any outliers

In [ ]:
df["salary"] = df["salary"].fillna()(df["salary"].median())  #numerical and data should contain  outliers

In [ ]:
df["salary"] = df["salary"].fillna()(df["salary"].mode())    #categorical and text kind of data

In [93]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [95]:
df.duplicated().sum()

0

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.drop_duplicates(
    subset = ["Income"]
    inplace= True
)

In [ ]:
df["Gender"]= df["Gender"].replace({
"M":"Male",
"F":"Female"
    
})

In [ ]:
df["Income"].unique()